/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentManagement;
import java.awt.Component;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Zerina Taznin Nova
 */
public class RentManagement extends javax.swing.JFrame {

    /**
     * Creates new form RentManagement
     */
    public RentManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ADDRESS = new javax.swing.JTextField();
        TELEPHONE = new javax.swing.JTextField();
        MOBILEPHONE = new javax.swing.JTextField();
        EMAIL = new javax.swing.JTextField();
        ExitMainPage = new javax.swing.JButton();
        UploadCustomerInfo = new javax.swing.JButton();
        CancelInput = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        accDetails = new javax.swing.JTextField();
        accName = new javax.swing.JTextField();
        accID = new javax.swing.JTextField();
        pCode = new javax.swing.JTextField();
        pDescrip = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        PurchaseForm = new javax.swing.JButton();
        RentalForm = new javax.swing.JButton();
        InventoryForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("Inventory Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("Customer Details:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("First Name: ");

        FN.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("Last Name: ");

        LN.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Address: ");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Telephone (If any):");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Mobile Phone: ");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setText("E-mail: ");

        ADDRESS.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        TELEPHONE.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        MOBILEPHONE.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        MOBILEPHONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBILEPHONEActionPerformed(evt);
            }
        });

        EMAIL.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        ExitMainPage.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        ExitMainPage.setText("Exit");
        ExitMainPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitMainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMainPageActionPerformed(evt);
            }
        });

        UploadCustomerInfo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        UploadCustomerInfo.setText("Upload");
        UploadCustomerInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UploadCustomerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadCustomerInfoActionPerformed(evt);
            }
        });

        CancelInput.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        CancelInput.setText("Cancel");
        CancelInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UploadCustomerInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExitMainPage))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MOBILEPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TELEPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(FN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TELEPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(MOBILEPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitMainPage)
                    .addComponent(CancelInput)
                    .addComponent(UploadCustomerInfo))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 480, 480));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setText("Account Info: ");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel11.setText("Payment Method: ");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("Account ID:");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setText("Account Name:");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel14.setText("Account Details (Optional):");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel15.setText("Payment Code:");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel16.setText("Payment Description: ");

        accDetails.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        accName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        accID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        pCode.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        pDescrip.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        pDescrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDescripActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))
                                        .addGap(110, 110, 110))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accID, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pCode, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(accID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(accName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(accDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(pDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 520, 390));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        PurchaseForm.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        PurchaseForm.setText("Purchase");
        PurchaseForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PurchaseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PurchaseFormMouseClicked(evt);
            }
        });
        PurchaseForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseFormActionPerformed(evt);
            }
        });

        RentalForm.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        RentalForm.setText("Rent");
        RentalForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RentalForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentalFormMouseClicked(evt);
            }
        });

        InventoryForm.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        InventoryForm.setText("Inventory");
        InventoryForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InventoryForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(PurchaseForm)
                .addGap(42, 42, 42)
                .addComponent(RentalForm)
                .addGap(38, 38, 38)
                .addComponent(InventoryForm)
                .addGap(49, 49, 49))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PurchaseForm)
                    .addComponent(RentalForm)
                    .addComponent(InventoryForm))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 520, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MOBILEPHONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBILEPHONEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOBILEPHONEActionPerformed

    private void pDescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDescripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pDescripActionPerformed

    private JFrame Frame;
            
    private void ExitMainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMainPageActionPerformed
        // TODO add your handling code here:
        
        Frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(Frame, "Do you want to Cancel?", "Inventory Management System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
        System.exit(0);
    }//GEN-LAST:event_ExitMainPageActionPerformed

    }
    
    private void CancelInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelInputActionPerformed
        // TODO add your handling code here:
        
        JTextField cleartext = null;
        
        for (Component c:jPanel2.getComponents())
        {
        if (c.getClass().toString().contains("javax.swing.JTextField"))
        {
            cleartext= (JTextField)c;
            cleartext.setText("");
        }
    }//GEN-LAST:event_CancelInputActionPerformed
    
        //==========================================================================

    for (Component c:jPanel3.getComponents())
        {
        if (c.getClass().toString().contains("javax.swing.JTextField"))
        {
            cleartext= (JTextField)c;
            cleartext.setText("");
        }
    }
        
    }
        
    private void InventoryFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryFormMouseClicked
        // TODO add your handling code here:
        
        InventoryForm ivnf = new InventoryForm();
        ivnf.setVisible(true);
        ivnf.pack();
        ivnf.setLocationRelativeTo(null);
        //ivnf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //this.dispose();
        
    }//GEN-LAST:event_InventoryFormMouseClicked

    private void RentalFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentalFormMouseClicked
        // TODO add your handling code here:
        
        RentalForm rtf = new RentalForm();
        rtf.setVisible(true);
        rtf.pack();
        rtf.setLocationRelativeTo(null);
        //rtf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //this.dispose();
        
    }//GEN-LAST:event_RentalFormMouseClicked

    private void PurchaseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchaseFormMouseClicked
        // TODO add your handling code here:
        
        PurchaseForm pcf = new PurchaseForm();
        pcf.setVisible(true);
        pcf.pack();
        pcf.setLocationRelativeTo(null);
        //pcf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //this.dispose();
        
    }//GEN-LAST:event_PurchaseFormMouseClicked

    private void UploadCustomerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadCustomerInfoActionPerformed
        // TODO add your handling code here:
        
        String cfname = FN.getText();
        String clname = LN.getText();
        String cAddress = ADDRESS.getText();
        String cTelephone = TELEPHONE.getText();
        String cMobile = MOBILEPHONE.getText();
        String cEmail = EMAIL.getText();
        
        String cAccID = accID.getText();
        String cAccName = accName.getText();
        String cAccDetails = accDetails.getText();
        
        String cPayCode = pCode.getText();
        String cPayDescription = pDescrip.getText();
        
        PreparedStatement st;
        String query = " INSERT INTO `customer`(`cFirstName`, `cLastName`, `cAddress`, `cTelephone`, `cMobilePhone`, `cEmail`) VALUES (?,?,?,?,?,?) "
                + "AND INSERT INTO `accounts`(`Account_ID`, `Account_Name`, `Account_Details`) VALUES (?,?,?)"
                + "INSERT INTO `payment_methods`(`Payment_Method_Code`, `Payment_Method_Description`) VALUES (?,?)";
        
        
        try {st = DatabaseConnection.getConnection().prepareStatement(query);
        st.setString(1, cfname);
        st.setString(2, clname);
        st.setString(3, cAddress);
        st.setString(4, cTelephone);
        st.setString(5, cMobile);
        st.setString(6, cEmail);
        
        st.setString(1, cAccID);
        st.setString(2, cAccName);
        st.setString(3, cAccDetails);
        
        st.setString(1, cPayCode);
        st.setString(2, cPayDescription);
        
        if(st.executeUpdate() > 0)
        {
        JOptionPane.showMessageDialog(null, "New customer info has been uploaded");
        }
        
        } catch (SQLException ex) {
        Logger.getLogger(RentManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UploadCustomerInfoActionPerformed

    private void PurchaseFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PurchaseFormActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADDRESS;
    private javax.swing.JButton CancelInput;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JButton ExitMainPage;
    private javax.swing.JTextField FN;
    private javax.swing.JButton InventoryForm;
    private javax.swing.JTextField LN;
    private javax.swing.JTextField MOBILEPHONE;
    private javax.swing.JButton PurchaseForm;
    private javax.swing.JButton RentalForm;
    private javax.swing.JTextField TELEPHONE;
    private javax.swing.JButton UploadCustomerInfo;
    private javax.swing.JTextField accDetails;
    private javax.swing.JTextField accID;
    private javax.swing.JTextField accName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField pCode;
    private javax.swing.JTextField pDescrip;
    // End of variables declaration//GEN-END:variables

}
